import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./componenst/Footer/footer";
import NavBar from "./componenst/Navbar/navbar";


const poppins = Poppins({
  weight: ['400','500','600','700'],  // choose the weights you need
  subsets: ['latin'],                 // choose the subsets you need
  variable: '--font-poppins',         // optional CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={poppins.variable}
      >
        <NavBar />
        {children}
        <Footer />

      </body>
    </html>
  );
}
